services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: pako
      MYSQL_PASSWORD: rek
      MYSQL_DATABASE: ELI
  eli_api:
    build: .
    ports:
      - 4300:4300
    depends_on:
      - db
